### ISSUE TITLE
hanging on loading page

### ISSUE THREAD

**Issue by Menyuska** [stephenpapierski/tablechamp-app#9]
Hey, followed all instructions and got stuck on a loading page. Any ideas please? (using chrome and firefox)

**Comment by stephenpapierski** [comment]
Easiest way to find out what's going on is to open the Developer Tools and see if there are any errors in the Console. You can do the same thing for Firefox by opening the Web Console. Maybe attach a screenshot from one of those consoles.

**Comment by stephenpapierski** [comment]
Closed due to no further information being provided.
